spring:
  application:
    name: bankingservice

  datasource:
    url: jdbc:postgresql://localhost:5432/banking_db
    username: ${DB_USERNAME:banking_user}
    password: ${DB_PASSWORD:banking_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}

  threads:
    virtual:
      enabled: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate: WARN
    org.springframework: INFO
    com.zaxxer.hikari: WARN
    org.apache: WARN
  pattern:
    console: "%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr([%thread]){cyan} %clr(%logger{36}){blue} - %msg%n"